app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # path('', views.index),
    path('index/', views.index, name="index"),

    #authentications
    path('login/', views.login_view, name="login"),
    path('register/', views.registration_view, name="register"),
    path('logout/', views.logout_view, name="logout"),

    path('administrator/', views.administrator_index, name="administrator"),
    path('add_agent/', views.add_agent, name="add_agent"),
    path('agent/', views.agent_index, name="agent"),
    path('lead/', views.lead_index, name="lead"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("app.urls")),
]

app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    is_admin = models.BooleanField('admin', default=False)
    is_agent = models.BooleanField('agent', default=False)
    is_lead = models.BooleanField('lead', default=False)

class Agent(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="agent")

    def __str__(self):
        return str(self.user)
    
class Lead(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    agent = models.ForeignKey(Agent, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

app/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from .models import User, Agent, Lead

class LoginForm(forms.Form):
    username = forms.CharField(label="Username",widget=forms.TextInput(attrs={'class':'border rounded px-2 w-[400px] h-[38px] mx-auto'}))
    password = forms.CharField(label="Password",widget=forms.PasswordInput(attrs={'class':'border rounded px-2 w-[400px] h-[38px] mx-auto'}))

    class Meta:
        model = User
        fields = ['username', 'password']

class RegistrationForm(UserCreationForm):
    username = forms.CharField(label="Username", widget=forms.TextInput(attrs={'class':'border rounded px-2 w-[400px] h-[38px] mx-auto'}))
    password1 = forms.CharField(label="Password",widget=forms.PasswordInput(attrs={'class':'border rounded px-2 w-[400px] h-[38px] mx-auto'}))
    password2 = forms.CharField(label="Confirm Password",widget=forms.PasswordInput(attrs={'class':'border rounded px-2 w-[400px] h-[38px] mx-auto'}))
    email = forms.CharField(label="Email",widget=forms.EmailInput(attrs={'class':'border rounded px-2 w-[400px] h-[38px] mx-auto'}))
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'is_admin', 'is_agent', 'is_lead')
    


class UserForm(forms.ModelForm):
    agent = forms.ModelChoiceField(queryset=User.objects.filter(is_agent=True), empty_label=None, label="Agent")

    class Meta:
        model = User
        fields = ['agent']

class CreateLead(forms.ModelForm):
    agent_search = User.objects.filter(is_lead=True)
    name = forms.ModelChoiceField(queryset=agent_search, empty_label=None, label="Lead Name")
    class Meta:
        model = User
        fields = ['name']

class CreateAgent(forms.ModelForm):
    agent = forms.ModelChoiceField(queryset=User.objects.filter(is_agent=True), empty_label=None, label="Agent")
    
    class Meta:
        model = User
        fields = ['agent']
    

app/templates/app/add_agent.html
{% extends 'base.html' %}

{% block title %}Administrator{% endblock title %}

{% block content %}

<div class="">
    <div class="grid grid-cols-12 gap-5">
        <div class="col-span-2 hidden md:block">Nash</div>
        <div class="col-span-10 lg:col-span-7 border-l pl-5">
            <div class="flex justify-between align-center mb-5">
                <span>Add agent</span>

            </div>
            <hr>
            <div class="mt-5">
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="mb-5">
                        {{form}}
                        {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                                {% endfor %}
                        </ul>
                        {% endif %}
                        </span>
                        <div class="mt-5">
                            <hr>
                            <input type="submit" value="create">
                        </div>
                </form>
            </div>
        </div>
        <div class="col-span-3 border-l pl-5 hidden lg:block">Nash</div>
    </div>
</div>



{% endblock content %}

<!-- <form action="" method="post">
    {% csrf_token %}
    {{form}}
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
    </ul>
    {% endif %}
    <input type="submit" value="create">
</form> -->

app/templates/app/admin_index.html
{% extends 'base.html' %}

{% block title %}Administrator{% endblock title %}

{% block content %}

<div class="">
    <div class="grid grid-cols-12 gap-5">
        <div class="col-span-2 hidden md:block">Nash</div>
        <div class="col-span-10 lg:col-span-7 border-l pl-5">
            <div class="flex justify-between align-center mb-5">
                <span>Select agent to change</span>
                <a href="{% url 'add_agent' %}" class="bg-blue-600 text-white px-3 py-1 rounded-md flex items-center">
                    <span class="px-2 font-bold">Add Agent</span>
                    <svg fill="white" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="15" height="15"
                        viewBox="0 0 24 24">
                        <path fill-rule="evenodd"
                            d="M 11 2 L 11 11 L 2 11 L 2 13 L 11 13 L 11 22 L 13 22 L 13 13 L 22 13 L 22 11 L 13 11 L 13 2 Z">
                        </path>
                    </svg>
                </a>
            </div>
            <hr>
            <div class="mt-5">
                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                        {% endfor %}
                </ul>
                {% endif %}
                <ul>
                    <li class="p-2">
                        {% if agent_list_count == 1 %}
                        {{agent_list_count}} Agent
                        {% else %}
                        {{agent_list_count}} Agents
                        {% endif %}</li>
                    {% for agent in agent_list %}
                    <li class="p-2"><a href="">{{agent.user}}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="col-span-3 border-l pl-5 hidden lg:block">Nash</div>
    </div>
</div>



{% endblock content %}

app/templates/app/agent.html
{% extends 'base.html' %}

{% block title %}Agent{% endblock title %}

{% block content %}

<p>Agent's Page</p>

<form action="" method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Register Agent">
</form>

<a href="{% url 'logout' %}">logout</a>
{% endblock content %}

app/templates/app/agent_index.html
{% extends 'base.html' %}

{% block title %}Agent{% endblock title %}

{% block content %}
<p>Agent's Page</p>
{% endblock content %}

app/templates/app/index.html
{% extends 'base.html' %}

{% block title %}Index{% endblock title %}

{% block content %}
<a href="{% url 'login' %}">login</a>
<a href="{% url 'register' %}">register</a>

{{request.user}}

<hr>
{% endblock content %}

app/templates/app/lead_index.html
{% extends 'base.html' %}

{% block title %}Lead{% endblock title %}

{% block content %}
<p>Leads Page</p>
<a href="{% url 'logout' %}">logout</a>
{% endblock content %}

app/templates/app/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock title %}

{% block content %}
<div class="flex items-center">
    <form action="" method="post" class="mx-auto">
        {% csrf_token %}
        <h1 class="bg-[#417690] text-center p-4 text-xl font-bold text-white">Pinacore Administrtion</h1>
        <div class=" p-10 shadow">

            <div class="flex flex-col mb-3">
                <label for="id_username" class="class':'px-3 w-[400px] h-[30px] mx-auto">Username</label>
                {{form.username}}
            </div>
            <div class="flex flex-col">
                <label for="id_password" class="class':'px-3 w-[400px] h-[30px] mx-auto">Password</label>
                {{form.password}}
            </div>
            <div class="flex justify-center  mt-8">
                <input type="submit" value="Login" class="bg-[#417690] text-white px-3 py-1 rounded-md ">
            </div>
            <p class="text-center mt-5">Don't have an account? <a class="text-red-500 font-bold"
                    href="{% url 'register' %}">Register</a></p>
        </div>
    </form>
</div>
{% endblock content %}

app/templates/app/logout.html
{% extends 'base.html' %}

{% block title %}Logout{% endblock title %}

{% block content %}
<div class="p-5">
    <p class="mb-3">Logged out</p>
    <p class="mb-3 text-[13px]">Thanks for spending some quality time with the web site today</p>
    <a class="text-blue-600" href="{% url 'login' %}">Log in again</a>

</div>


{% endblock content %}

app/templates/app/register.html
{% extends 'base.html' %}

{% block title %}Register{% endblock title %}

{% block content %}
<div class="flex items-center">
    <form action="" method="post" class="mx-auto">
        {% csrf_token %}
        <h1 class="bg-[#417690] text-center p-4 text-xl font-bold text-white">Pinacore Administration</h1>
        <div class="p-10 shadow">

            <div class="flex flex-col mb-3">
                <label for="id_username" class="class':'px-3 w-[400px] h-[30px] mx-auto">Username</label>
                {{form.username}}
            </div>
            <div class="flex flex-col mb-3">
                <label for="id_email" class="class':'px-3 w-[400px] h-[30px] mx-auto">Email</label>
                {{form.email}}
            </div>

            <div class="flex flex-col">
                <label for="id_password1" class="class':'px-3 w-[400px] h-[30px] mx-auto">Password</label>
                {{form.password1}}
            </div>

            <div class="flex flex-col">
                <label for="id_password2" class="class':'px-3 w-[400px] h-[30px] mx-auto">Password</label>
                {{form.password2}}
            </div>

            <div class="flex justify-center items-center mt-5">
                <div class="flex flex-col mx-4">
                    <label for="id_is_admin" class="mx-auto">Admin</label>
                    <input id="id_is_admin" name="role" value="admin">
                </div>

                <div class="flex flex-col mx-4">
                    <label for="id_is_agent" class="mx-auto">Agent</label>
                    <input id="id_is_agent" name="role" value="agent">
                </div>

                <div class="flex flex-col mx-4">
                    <label for="id_is_lead" class="mx-auto">Lead</label>
                    <input id="id_is_lead" name="role" value="lead">
                </div>
            </div>





            <div class="flex justify-center mt-8">
                <input type="submit" value="Register" class="bg-[#417690] text-white px-3 py-1 rounded-md">
            </div>
            <p class="text-center mt-5">Already have an account? <a class="text-red-500 font-bold"
                    href="{% url 'login' %}">Login</a></p>
        </div>
    </form>
</div>
{% endblock content %}